name: Poll BabyBitcoin

on:
  schedule:
    - cron: "* * * * *"

jobs:
  poll:
    runs-on: ubuntu-latest
    env:
      ADDRESS_BSC:        ${{ secrets.ADDRESS_BSC }}
      ADDRESS_ETH:        ${{ secrets.ADDRESS_ETH }}
      BSCSCAN_API_KEY:    ${{ secrets.BSCSCAN_API_KEY }}
      ETHERSCAN_API_KEY:  ${{ secrets.ETHERSCAN_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
      POLL_SECONDS:       "15"
      TOKEN_NAME:         BabyBitcoin
      TOKEN_SYMBOL:       BBTC
      BUY_URL:            https://www.bitcoin-baby.com/buy
      PRICE_PER_COIN_USD: "0.012"
      LAUNCH_PRICE_USD:   "0.03"
      HEADER_GIF_URL:     https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExbDR3eHI0eW9kanB3ZjdiOWgyazJ3djE2b3dreDk1YWZsNmJibGloNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/smaaKxR6ZrQYQxHFfA/giphy.gif
      FIXED_BNB_USD:      "795"
      FIXED_ETH_USD:      ""
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run polling script once
        run: python bot.py
